language: go

go:
  - 1.7
  - tip

go_import_path: github.com/microlib/usermanager

install:
  - go get golang.org/x/tools/cmd/cover
  - go get github.com/mattn/goveralls

script:
  - go test ./...
  - $HOME/gopath/bin/goveralls -service=travis-ci
  
notifications:
  slack: microlib:LMRLKmZEldpHe2FQv6Pszuzu
